// Script para actualizar todas las palabras con pistas fáciles/difíciles y agregar categoría privada

const newWordsByTheme = {
    "comida_argentina": [
        { word: "ASADO", easyHint: "Fuego", hardHint: "Domingo" },
        { word: "EMPANADA", easyHint: "Masa", hardHint: "Tucumán" },
        { word: "MILANESA", easyHint: "Rebozado", hardHint: "Italiana" },
        { word: "CHORIPAN", easyHint: "Sandwich", hardHint: "Cancha" },
        { word: "LOCRO", easyHint: "Guiso", hardHint: "Mayo" },
        { word: "MATAMBRE", easyHint: "Relleno", hardHint: "Enrollado" },
        { word: "HUMITA", easyHint: "Choclo", hardHint: "Amarillo" },
        { word: "PROVOLETA", easyHint: "Parrilla", hardHint: "Derretido" },
        { word: "BONDIOLA", easyHint: "Cerdo", hardHint: "Ahumado" },
        { word: "MORCILLA", easyHint: "Negro", hardHint: "Sangre" },
        { word: "CHINCHULÍN", easyHint: "Tripa", hardHint: "Crocante" },
        { word: "MOLLEJA", easyHint: "Glándula", hardHint: "Tierna" },
        { word: "ALFAJOR", easyHint: "Dulce", hardHint: "Havanna" },
        { word: "FACTURAS", easyHint: "Panadería", hardHint: "Domingo" },
        { word: "MEDIALUNAS", easyHint: "Cuerno", hardHint: "Manteca" }
    ],
    "bebidas_argentinas": [
        { word: "MATE", easyHint: "Calabaza", hardHint: "Compartir" },
        { word: "FERNET", easyHint: "Amargo", hardHint: "Córdoba" },
        { word: "QUILMES", easyHint: "Dorada", hardHint: "Nacional" },
        { word: "MALBEC", easyHint: "Tinto", hardHint: "Mendoza" },
        { word: "TORRONTÉS", easyHint: "Blanco", hardHint: "Aromático" },
        { word: "GANCIA", easyHint: "Aperitivo", hardHint: "Batido" },
        { word: "CAMPARI", easyHint: "Rojo", hardHint: "Italiano" },
        { word: "LICUADO", easyHint: "Batido", hardHint: "Fruta" },
        { word: "SUBMARINO", easyHint: "Chocolate", hardHint: "Caliente" },
        { word: "CORTADO", easyHint: "Café", hardHint: "Pequeño" },
        { word: "LAGRIMA", easyHint: "Leche", hardHint: "Gotita" },
        { word: "GINEBRA", easyHint: "Destilado", hardHint: "Transparente" },
        { word: "HESPERIDINA", easyHint: "Naranja", hardHint: "Amargo" },
        { word: "APEROL", easyHint: "Italiano", hardHint: "Spritz" },
        { word: "TERMA", easyHint: "Caliente", hardHint: "Recipiente" }
    ],
    "futbol_argentino": [
        { word: "BOCA", easyHint: "Azul", hardHint: "Xeneize" },
        { word: "RIVER", easyHint: "Banda", hardHint: "Millonario" },
        { word: "MARADONA", easyHint: "Diez", hardHint: "Dios" },
        { word: "MESSI", easyHint: "Pulga", hardHint: "Rosario" },
        { word: "BOMBONERA", easyHint: "Estadio", hardHint: "Chocolate" },
        { word: "MONUMENTAL", easyHint: "Núñez", hardHint: "Grande" },
        { word: "SUPERCLÁSICO", easyHint: "Rivalidad", hardHint: "Partido" },
        { word: "ESTUDIANTES", easyHint: "Pincha", hardHint: "Plata" },
        { word: "RACING", easyHint: "Academia", hardHint: "Avellaneda" },
        { word: "INDEPENDIENTE", easyHint: "Rojo", hardHint: "Rey" },
        { word: "HURACÁN", easyHint: "Globo", hardHint: "Parque" },
        { word: "LANÚS", easyHint: "Granate", hardHint: "Fortaleza" },
        { word: "TALLERES", easyHint: "Córdoba", hardHint: "Matador" },
        { word: "BELGRANO", easyHint: "Celeste", hardHint: "Pirata" },
        { word: "INSTITUTO", easyHint: "Gloria", hardHint: "Alberdi" }
    ],
    "lugares_argentina": [
        { word: "CAMINITO", easyHint: "Colorido", hardHint: "Boca" },
        { word: "IGUAZÚ", easyHint: "Cataratas", hardHint: "Frontera" },
        { word: "MENDOZA", easyHint: "Vino", hardHint: "Cuyo" },
        { word: "BARILOCHE", easyHint: "Lagos", hardHint: "Chocolate" },
        { word: "SALTA", easyHint: "Norte", hardHint: "Linda" },
        { word: "USHUAIA", easyHint: "Fin", hardHint: "Mundo" },
        { word: "TIGRE", easyHint: "Delta", hardHint: "Río" },
        { word: "ROSARIO", easyHint: "Bandera", hardHint: "Cuna" },
        { word: "CALAFATE", easyHint: "Glaciar", hardHint: "Perito" },
        { word: "CAFAYATE", easyHint: "Valles", hardHint: "Torrontés" },
        { word: "TILCARA", easyHint: "Quebrada", hardHint: "Humahuaca" },
        { word: "PENÍNSULA", easyHint: "Valdés", hardHint: "Ballenas" },
        { word: "ACONCAGUA", easyHint: "Cumbre", hardHint: "América" },
        { word: "OBELISCO", easyHint: "Monumento", hardHint: "Avenida" },
        { word: "RECOLETA", easyHint: "Cementerio", hardHint: "Evita" }
    ],
    "cordobes": [
        { word: "CUARTETO", easyHint: "Ritmo", hardHint: "Baile" },
        { word: "MONA", easyHint: "Jiménez", hardHint: "Mandril" },
        { word: "FERNET", easyHint: "Cola", hardHint: "Branca" },
        { word: "SIERRAS", easyHint: "Montañas", hardHint: "Punilla" },
        { word: "DOCTA", easyHint: "Universidad", hardHint: "Córdoba" },
        { word: "PEÑA", easyHint: "Folklore", hardHint: "Jesús" },
        { word: "CHAMUYAR", easyHint: "Conversar", hardHint: "Hablar" },
        { word: "CULIAU", easyHint: "Expresión", hardHint: "Cordobés" },
        { word: "BOLUDO", easyHint: "Amigo", hardHint: "Che" },
        { word: "BONDI", easyHint: "Transporte", hardHint: "Público" },
        { word: "BIRRA", easyHint: "Cerveza", hardHint: "Fría" },
        { word: "ASADITO", easyHint: "Reunión", hardHint: "Amigos" },
        { word: "VILLA", easyHint: "Carlos", hardHint: "Paz" },
        { word: "CARLOS", easyHint: "Paz", hardHint: "Villa" },
        { word: "COSQUÍN", easyHint: "Festival", hardHint: "Folklore" }
    ],
    "tango_folklore": [
        { word: "GARDEL", easyHint: "Zorzal", hardHint: "Criollo" },
        { word: "BANDONEÓN", easyHint: "Instrumento", hardHint: "Acordeón" },
        { word: "MILONGA", easyHint: "Baile", hardHint: "Tango" },
        { word: "PIAZZOLLA", easyHint: "Astor", hardHint: "Libertango" },
        { word: "CHACARERA", easyHint: "Folclore", hardHint: "Santiago" },
        { word: "ZAMBA", easyHint: "Pañuelo", hardHint: "Alfonsina" },
        { word: "VIDALA", easyHint: "Canto", hardHint: "Triste" },
        { word: "MALAMBO", easyHint: "Zapateo", hardHint: "Gaucho" },
        { word: "PAYADOR", easyHint: "Improvisación", hardHint: "Guitarra" },
        { word: "GAUCHO", easyHint: "Campo", hardHint: "Pampa" },
        { word: "FACÓN", easyHint: "Cuchillo", hardHint: "Gaucho" },
        { word: "PONCHO", easyHint: "Abrigo", hardHint: "Lana" },
        { word: "ALPARGATAS", easyHint: "Calzado", hardHint: "Cáñamo" },
        { word: "BOMBACHA", easyHint: "Pantalón", hardHint: "Gaucho" },
        { word: "BOINA", easyHint: "Gorro", hardHint: "Vasca" }
    ],
    "politica_historia": [
        { word: "EVITA", easyHint: "Abanderada", hardHint: "Humildes" },
        { word: "PERÓN", easyHint: "General", hardHint: "Justicialismo" },
        { word: "BELGRANO", easyHint: "Bandera", hardHint: "Manuel" },
        { word: "SARMIENTO", easyHint: "Educación", hardHint: "Domingo" },
        { word: "ROCA", easyHint: "Desierto", hardHint: "Conquista" },
        { word: "YRIGOYEN", easyHint: "Radical", hardHint: "Hipólito" },
        { word: "MALVINAS", easyHint: "Islas", hardHint: "Guerra" },
        { word: "MAYO", easyHint: "Revolución", hardHint: "1810" },
        { word: "CABILDO", easyHint: "Colonial", hardHint: "Abierto" },
        { word: "INDEPENDENCIA", easyHint: "Tucumán", hardHint: "1816" },
        { word: "LIBERTADOR", easyHint: "San", hardHint: "Martín" },
        { word: "CRUZADA", easyHint: "Andes", hardHint: "Libertadora" },
        { word: "ROSARIO", easyHint: "Bandera", hardHint: "Cuna" },
        { word: "CONGRESO", easyHint: "Nacional", hardHint: "Diputados" },
        { word: "CASA", easyHint: "Rosada", hardHint: "Gobierno" }
    ],
    "transporte": [
        { word: "SUBTE", easyHint: "Subterráneo", hardHint: "Metro" },
        { word: "COLECTIVO", easyHint: "Urbano", hardHint: "Línea" },
        { word: "REMISE", easyHint: "Radio", hardHint: "Taxi" },
        { word: "TAXI", easyHint: "Amarillo", hardHint: "Bandera" },
        { word: "TREN", easyHint: "Riel", hardHint: "Vagón" },
        { word: "COMBI", easyHint: "Minibús", hardHint: "Escolar" },
        { word: "TROLEBÚS", easyHint: "Eléctrico", hardHint: "Cable" },
        { word: "LANCHA", easyHint: "Río", hardHint: "Tigre" },
        { word: "AVIÓN", easyHint: "Vuelo", hardHint: "Aeropuerto" },
        { word: "MOTO", easyHint: "Delivery", hardHint: "Rappi" },
        { word: "BICICLETA", easyHint: "Pedal", hardHint: "Ecobici" },
        { word: "UBER", easyHint: "App", hardHint: "Viaje" },
        { word: "CABIFY", easyHint: "Aplicación", hardHint: "Premium" },
        { word: "METROBUS", easyHint: "Carril", hardHint: "Exclusivo" },
        { word: "PEAJE", easyHint: "Pago", hardHint: "Autopista" }
    ],
    "animales_pampa": [
        { word: "CARPINCHO", easyHint: "Roedor", hardHint: "Grande" },
        { word: "HORNERO", easyHint: "Nido", hardHint: "Barro" },
        { word: "ÑANDÚ", easyHint: "Corredor", hardHint: "Avestruz" },
        { word: "VIZCACHA", easyHint: "Madriguera", hardHint: "Conejo" },
        { word: "CHIMANGO", easyHint: "Carroñero", hardHint: "Halcón" },
        { word: "BENTEVEO", easyHint: "Canto", hardHint: "Amarillo" },
        { word: "TERO", easyHint: "Grito", hardHint: "Protector" },
        { word: "CARANCHO", easyHint: "Rapaz", hardHint: "Campo" },
        { word: "MARTINETA", easyHint: "Perdiz", hardHint: "Copetona" },
        { word: "MULITA", easyHint: "Armadillo", hardHint: "Peludo" },
        { word: "ZORRINO", easyHint: "Olor", hardHint: "Rayado" },
        { word: "COMADREJA", easyHint: "Pequeña", hardHint: "Carnívora" },
        { word: "LIEBRE", easyHint: "Veloz", hardHint: "Orejas" },
        { word: "YACARÉ", easyHint: "Reptil", hardHint: "Cocodrilo" },
        { word: "DORADO", easyHint: "Pez", hardHint: "Río" }
    ],
    "lunfardo_jerga": [
        { word: "LABURO", easyHint: "Trabajo", hardHint: "Ocupación" },
        { word: "GUITA", easyHint: "Dinero", hardHint: "Plata" },
        { word: "PIBE", easyHint: "Chico", hardHint: "Joven" },
        { word: "MINA", easyHint: "Mujer", hardHint: "Chica" },
        { word: "CHABON", easyHint: "Tipo", hardHint: "Hombre" },
        { word: "MORFAR", easyHint: "Comer", hardHint: "Alimentarse" },
        { word: "FIACA", easyHint: "Pereza", hardHint: "Desgano" },
        { word: "QUILOMBO", easyHint: "Lío", hardHint: "Desorden" },
        { word: "CHAMUYAR", easyHint: "Hablar", hardHint: "Conversar" },
        { word: "BONDI", easyHint: "Colectivo", hardHint: "Transporte" },
        { word: "BIRRA", easyHint: "Cerveza", hardHint: "Bebida" },
        { word: "MANGO", easyHint: "Peso", hardHint: "Moneda" },
        { word: "TRUCHO", easyHint: "Falso", hardHint: "Mentira" },
        { word: "GROSO", easyHint: "Grande", hardHint: "Importante" },
        { word: "ZAFAR", easyHint: "Escapar", hardHint: "Salvarse" }
    ],
    "categoria_privada": [
        // Drogas conocidas
        { word: "CANNABIS", easyHint: "Marihuana", hardHint: "Verde" },
        { word: "PORRO", easyHint: "Marihuana", hardHint: "Papel" },
        { word: "MERCA", easyHint: "Cocaína", hardHint: "Blanca" },
        { word: "FASO", easyHint: "Cigarrillo", hardHint: "Hierba" },
        { word: "PASTILLA", easyHint: "Éxtasis", hardHint: "Fiesta" },

        // Personajes históricos polémicos
        { word: "ESCOBAR", easyHint: "Pablo", hardHint: "Colombia" },
        { word: "CHAPO", easyHint: "Guzmán", hardHint: "México" },
        { word: "CAPONE", easyHint: "Al", hardHint: "Chicago" },

        // Eventos históricos
        { word: "TORRES", easyHint: "Gemelas", hardHint: "Septiembre" },
        { word: "TITANIC", easyHint: "Barco", hardHint: "Iceberg" },
        { word: "HIROSHIMA", easyHint: "Bomba", hardHint: "Japón" },
        { word: "CHERNOBYL", easyHint: "Nuclear", hardHint: "Reactor" },

        // Fútbol argentino polémico
        { word: "DESCENSO", easyHint: "River", hardHint: "B" },
        { word: "FANTASMA", easyHint: "B", hardHint: "Nacional" },
        { word: "BARRABRAVA", easyHint: "Hinchada", hardHint: "Violenta" },
        { word: "DOPING", easyHint: "Maradona", hardHint: "Mundial" },

        // Política argentina polémica
        { word: "CORRALITO", easyHint: "2001", hardHint: "Bancos" },
        { word: "HELICOPTERO", easyHint: "Presidencial", hardHint: "López" },
        { word: "INDULTOS", easyHint: "Menem", hardHint: "Perdón" },
        { word: "MALVERSACIÓN", easyHint: "Corrupción", hardHint: "Dinero" },

        // Temas actuales/woke
        { word: "FEMINISTA", easyHint: "Mujer", hardHint: "Igualdad" },
        { word: "MACHIRULO", easyHint: "Machista", hardHint: "Hombre" },
        { word: "VEGANO", easyHint: "Plantas", hardHint: "Animal" },
        { word: "AMBIENTALISTA", easyHint: "Planeta", hardHint: "Verde" },
        { word: "LIBERTARIO", easyHint: "Milei", hardHint: "Libre" },
        { word: "ZURDO", easyHint: "Izquierda", hardHint: "Comunista" },
        { word: "FACHO", easyHint: "Derecha", hardHint: "Fascista" },
        { word: "GLOBOLUDO", easyHint: "Clarín", hardHint: "Opositor" },
        { word: "PLANERO", easyHint: "Subsidio", hardHint: "Vago" },
        { word: "CHETO", easyHint: "Rico", hardHint: "Snob" }
    ]
};

console.log('Nuevas palabras con pistas fáciles/difíciles y categoría privada:');
console.log(JSON.stringify(newWordsByTheme, null, 2));
